title: yeno.studio
description: We shape useful digital products, then help them earn a place in people's lives.
url: https://yeno.studio
baseurl: ""
permalink: /journal/:slug/
timezone: Asia/Jakarta
future: false
markdown: kramdown
plugins:
  - jekyll-feed
feed:
  path: feed.xml
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
