title: yeno.studio
description: Yeno is a digital marketing and product development agency. We build digital products and run campaigns that grow them.
url: https://yeno.studio
baseurl: ""
permalink: /journal/:slug/
timezone: Asia/Jakarta
future: false
markdown: kramdown
plugins:
  - jekyll-feed
feed:
  path: feed.xml
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
